### ISSUE TITLE
Help for STM32 Timer Tutorial ⌚ // TRIAC Control ✅

### ISSUE THREAD

**Issue by zoroMdeD** [haseebzaib/Engineering-Portfolio#1]
Hello Haseeb,  we talking in youtube on comments, but youtube delete all message with email on comments, please send your project on my email: Morozov.M.biz@yandex.ru

**Comment by haseebzaib** [comment]
https://drive.google.com/drive/folders/1OJ1ebmHPk5cQmU8jDgFsGyyGDyoKTjdo


Here this is the drive link with project in it

**Comment by zoroMdeD** [comment]
Thank you so much, friend, you can hope for me any help.)
